### PR TITLE
[Authentication] Added basic http authenticatio non all endpoints

### PR DESCRIPTION
**Pull request by aistoica**
Basic authentication implementation for the petclinic spring boot application.
All APIs are secured and they require authentication and authorization to access.

### CODE REVIEW

**Comment by vfedoriv** [comment]
Nice, thanks.
But can you figure out how to make security optional ?
We need simple method to enable/disable security and small topic about it in readme.
As I understand, 
```
security.ignored=/**
spring.security.enabled=false
management.security.enabled=false
security.basic.enabled=false  
```
in application.properties not enought.
P.S.
I have unfinished Oauth2 security implementation for this project, so this can be usefull.

**Comment by vfedoriv** [comment]
So, I can wait for this changes or can create new branch "security", you push current work to new branch. Then, after make changes, I merge "security" branch with "master".

**Comment by aistoica** [comment]
So we want to merge the basic authentication and the Oauth2 branches?

As for feedback from the first message, I will try and get it done by tomorrow :)

**Comment by vfedoriv** [comment]
I just created "security" branches in this repo and in angular frontend repo - this current state my oauth2 security implementation.  As you can see - it very draft realization (work, but need improvement on both sides).
So, at first I merge you basic authentication **in master**. 
Later, oauth2 branch should be improved and then will be merged in master as one of security option.
@arey , what do you think ?

**Comment by vfedoriv** [comment]
merged, thanks

**Comment by arey** [comment]
Having both HTTP Basic and OAuth 2 (or OpenID Connect) authentication mechanism looks like very interesting. 
@vfedoriv are you planning to reuse the ```Role``` and ```User``` entities?

In the @aistoica contribution (thanks a lot), I'm not very familiar with using a ```Roles``` bean to declare constant and reuse them into ```@PreAuthorize( "hasRole(@roles.OWNER_ADMIN)" )```. @aistoica, is it a good practice?

**Comment by aistoica** [comment]
@arey, I found this on a spring guide when talking about security. It is simpler to use the roles declared on a bean because role names may change.

Having both options available in the project and just enabling the desired one seems very interesting. Looking forward for it :)

**Pull request merged**
