### PR TITLE
Add Springdoc to avoid workaround for springfox issue 3462

### LINKED ISSUE #89: Migrate from Springfox to Springdoc
Could avoid the workaround in https://github.com/spring-petclinic/spring-petclinic-rest/blob/master/src/main/java/org/springframework/samples/petclinic/config/SwaggerConfig.java

### PR DESCRIPTION
**Pull request by suryaprakashraja**
fix #89

### CODE REVIEW

**Comment by arey** [comment]
Thank you @suryaprakashraja for the PR. There is a lot of reformatting. Could you keep the current format in order we could see only the changes due to the Springdoc integration and Springfox removal?

**Comment by arey** [comment]
There are still some imports reorder that hide your changes. Could you please revert them?

**Comment by suryaprakashraja** [comment]
Fixed import re-order.

**Comment by arey** [comment]
Thanks a lot @suryaprakashraja

**Pull request merged**
