### PR TITLE
Upgrade to Spring Boot 2.1.5

### PR DESCRIPTION
**Pull request by arey**
Hi Vitaliy, this repo was still not upgraded to Spring Boot 2. Is you are.

### CODE REVIEW

**Comment by vfedoriv** [comment]
Hi Antoine.
Can you check if swagger doc works ok after upgrade (I remember springfox 2.9 have some issues with SpringBot 2 version)?
P.S.
And, I guess we should replace oraclejdk8 to openjdk8, to pass build check.

**Comment by arey** [comment]
I didn't upgrade Springfox. I will in a next PR. 
Changing the travis build top openjdk8 fix the build.
The Swagger UI is working http://localhost:9966/petclinic/swagger-ui.html
Before merging the PR, I will test the Angular UI.

**Comment by vfedoriv** [comment]
> The Swagger UI is working http://localhost:9966/petclinic/swagger-ui.html
that's what I meant. thanks

**Comment by arey** [comment]
The Angular Frontend is still working :)

**Pull request merged**
